import { relations, sql } from 'drizzle-orm'
import { boolean, index, integer, jsonb, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid, varchar } from 'drizzle-orm/pg-core'

const timestamps = { createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() }

export const eventStatus = pgEnum('event_status', ['DRAFT', 'UPCOMING', 'ONGOING', 'COMPLETED', 'ARCHIVED'])
export const userRole = pgEnum('user_role', ['SUPER_ADMIN', 'EVENT_ADMIN', 'SCORER'])
export const membershipRole = pgEnum('membership_role', ['EVENT_ADMIN', 'SCORER'])
export const matchStatus = pgEnum('match_status', ['SCHEDULED', 'READY', 'LIVE', 'PAUSED', 'COMPLETED', 'CANCELLED'])
export const assignmentStatus = pgEnum('assignment_status', ['ACTIVE', 'REVOKED'])
export const scoreEventStatus = pgEnum('score_event_status', ['POSTED', 'UNDONE'])

export const users = pgTable('users', { id: uuid('id').defaultRandom().primaryKey(), username: varchar('username', { length: 64 }).notNull(), passwordHash: text('password_hash').notNull(), displayName: varchar('display_name', { length: 160 }).notNull(), role: userRole('role').default('SCORER').notNull(), isActive: boolean('is_active').default(true).notNull(), ...timestamps }, (t) => [uniqueIndex('users_username_idx').on(t.username)])
export const sessions = pgTable('sessions', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), tokenHash: text('token_hash').notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), ...timestamps }, (t) => [uniqueIndex('sessions_token_hash_idx').on(t.tokenHash)])
export const events = pgTable('events', { id: uuid('id').defaultRandom().primaryKey(), name: varchar('name', { length: 200 }).notNull(), slug: varchar('slug', { length: 220 }).notNull(), description: text('description'), startDate: timestamp('start_date', { withTimezone: true }).notNull(), endDate: timestamp('end_date', { withTimezone: true }).notNull(), location: varchar('location', { length: 240 }), status: eventStatus('status').default('DRAFT').notNull(), createdBy: uuid('created_by').notNull().references(() => users.id), ...timestamps }, (t) => [uniqueIndex('events_slug_idx').on(t.slug)])
export const eventMembers = pgTable('event_members', { eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'cascade' }), userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }), role: membershipRole('role').notNull(), ...timestamps }, (t) => [primaryKey({ columns: [t.eventId, t.userId] }), index('event_members_user_idx').on(t.userId)])
export const sports = pgTable('sports', { id: uuid('id').defaultRandom().primaryKey(), name: varchar('name', { length: 100 }).notNull(), slug: varchar('slug', { length: 120 }).notNull(), ...timestamps }, (t) => [uniqueIndex('sports_slug_idx').on(t.slug)])
export const eventSports = pgTable('event_sports', { eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'cascade' }), sportId: uuid('sport_id').notNull().references(() => sports.id), ...timestamps }, (t) => [primaryKey({ columns: [t.eventId, t.sportId] })])
export const teams = pgTable('teams', { id: uuid('id').defaultRandom().primaryKey(), eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'cascade' }), name: varchar('name', { length: 160 }).notNull(), shortName: varchar('short_name', { length: 40 }), ...timestamps })
export const players = pgTable('players', { id: uuid('id').defaultRandom().primaryKey(), displayName: varchar('display_name', { length: 160 }).notNull(), firstName: varchar('first_name', { length: 80 }), lastName: varchar('last_name', { length: 80 }), photoUrl: text('photo_url'), status: varchar('status', { length: 32 }).default('ACTIVE').notNull(), ...timestamps })
export const teamPlayers = pgTable('team_players', { teamId: uuid('team_id').notNull().references(() => teams.id, { onDelete: 'cascade' }), playerId: uuid('player_id').notNull().references(() => players.id, { onDelete: 'cascade' }), jerseyNumber: integer('jersey_number'), status: varchar('status', { length: 32 }).default('ACTIVE').notNull(), ...timestamps }, (t) => [primaryKey({ columns: [t.teamId, t.playerId] })])
export const courts = pgTable('courts', { id: uuid('id').defaultRandom().primaryKey(), eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'cascade' }), name: varchar('name', { length: 120 }).notNull(), ...timestamps })
export const tournaments = pgTable('tournaments', { id: uuid('id').defaultRandom().primaryKey(), eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'cascade' }), eventSportId: uuid('event_sport_id').notNull(), name: varchar('name', { length: 160 }).notNull(), ...timestamps })
export const stages = pgTable('stages', { id: uuid('id').defaultRandom().primaryKey(), tournamentId: uuid('tournament_id').notNull().references(() => tournaments.id, { onDelete: 'cascade' }), name: varchar('name', { length: 120 }).notNull(), sortOrder: integer('sort_order').default(0).notNull(), ...timestamps })
export const matches = pgTable('matches', { id: uuid('id').defaultRandom().primaryKey(), eventId: uuid('event_id').notNull().references(() => events.id, { onDelete: 'cascade' }), eventSportId: uuid('event_sport_id').notNull(), tournamentId: uuid('tournament_id').references(() => tournaments.id), stageId: uuid('stage_id').references(() => stages.id), courtId: uuid('court_id').references(() => courts.id), scheduledStart: timestamp('scheduled_start', { withTimezone: true }), actualStart: timestamp('actual_start', { withTimezone: true }), actualEnd: timestamp('actual_end', { withTimezone: true }), status: matchStatus('status').default('READY').notNull(), ...timestamps }, (t) => [index('matches_event_idx').on(t.eventId), index('matches_court_idx').on(t.courtId), index('matches_status_idx').on(t.status)])
export const matchParticipants = pgTable('match_participants', { matchId: uuid('match_id').notNull().references(() => matches.id, { onDelete: 'cascade' }), participantKey: varchar('participant_key', { length: 40 }).notNull(), teamId: uuid('team_id').references(() => teams.id), seed: integer('seed'), ...timestamps }, (t) => [primaryKey({ columns: [t.matchId, t.participantKey] })])
export const matchScorers = pgTable('match_scorers', { matchId: uuid('match_id').notNull().references(() => matches.id, { onDelete: 'cascade' }), userId: uuid('user_id').notNull().references(() => users.id), assignedBy: uuid('assigned_by').notNull().references(() => users.id), assignedAt: timestamp('assigned_at', { withTimezone: true }).defaultNow().notNull(), status: assignmentStatus('status').default('ACTIVE').notNull() }, (t) => [primaryKey({ columns: [t.matchId, t.userId] }), index('match_scorers_user_idx').on(t.userId)])
export const scoreEvents = pgTable('score_events', { id: uuid('id').defaultRandom().primaryKey(), matchId: uuid('match_id').notNull().references(() => matches.id, { onDelete: 'cascade' }), clientEventId: varchar('client_event_id', { length: 120 }).notNull(), participantKey: varchar('participant_key', { length: 40 }).notNull(), eventType: varchar('event_type', { length: 80 }).notNull(), points: integer('points').notNull(), period: integer('period'), sequenceNumber: integer('sequence_number').notNull(), metadata: jsonb('metadata'), createdBy: uuid('created_by').notNull().references(() => users.id), status: scoreEventStatus('status').default('POSTED').notNull(), undoneAt: timestamp('undone_at', { withTimezone: true }), ...timestamps }, (t) => [uniqueIndex('score_events_idempotency_idx').on(t.matchId, t.clientEventId), uniqueIndex('score_events_match_sequence_idx').on(t.matchId, t.sequenceNumber)])
export const matchStates = pgTable('match_states', { matchId: uuid('match_id').primaryKey().references(() => matches.id, { onDelete: 'cascade' }), homeScore: integer('home_score').default(0).notNull(), awayScore: integer('away_score').default(0).notNull(), currentPeriod: integer('current_period').default(1).notNull(), periodState: jsonb('period_state'), clockState: jsonb('clock_state'), matchStatus: matchStatus('match_status').default('READY').notNull(), version: integer('version').default(0).notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() })
export const standings = pgTable('standings', { id: uuid('id').defaultRandom().primaryKey(), tournamentId: uuid('tournament_id').notNull().references(() => tournaments.id, { onDelete: 'cascade' }), teamId: uuid('team_id').notNull().references(() => teams.id, { onDelete: 'cascade' }), rank: integer('rank'), played: integer('played').default(0).notNull(), wins: integer('wins').default(0).notNull(), losses: integer('losses').default(0).notNull(), points: integer('points').default(0).notNull(), ...timestamps }, (t) => [uniqueIndex('standings_tournament_team_idx').on(t.tournamentId, t.teamId)])
export const results = pgTable('results', { matchId: uuid('match_id').primaryKey().references(() => matches.id, { onDelete: 'cascade' }), winnerParticipantKey: varchar('winner_participant_key', { length: 40 }), summary: jsonb('summary'), completedAt: timestamp('completed_at', { withTimezone: true }).notNull(), ...timestamps })
export const auditLogs = pgTable('audit_logs', { id: uuid('id').defaultRandom().primaryKey(), actorUserId: uuid('actor_user_id').references(() => users.id), entityType: varchar('entity_type', { length: 80 }).notNull(), entityId: uuid('entity_id'), action: varchar('action', { length: 80 }).notNull(), metadata: jsonb('metadata'), ...timestamps })

export const usersRelations = relations(users, ({ many }) => ({ sessions: many(sessions), memberships: many(eventMembers) }))
export const eventsRelations = relations(events, ({ many }) => ({ memberships: many(eventMembers), sports: many(eventSports), teams: many(teams), matches: many(matches) }))
export const matchesRelations = relations(matches, ({ one, many }) => ({ event: one(events, { fields: [matches.eventId], references: [events.id] }), participants: many(matchParticipants), scorers: many(matchScorers), scoreEvents: many(scoreEvents), state: one(matchStates), result: one(results) }))

export const seededSports = [{ name: 'Basketball', slug: 'basketball' }, { name: 'Volleyball', slug: 'volleyball' }, { name: 'Badminton', slug: 'badminton' }] as const

export const nonNegative = sql`check (points >= 0)`
