'use client'

import { useEffect, useState, useTransition } from 'react'
import { postSportScore, setBasketballStatus, undoLastBasketballScore } from '@/app/scorer/actions'

type Props = { matchId: string; sport?: 'basketball' | 'volleyball' | 'badminton'; initialState: { match: { id: string }; state?: { homeScore: number; awayScore: number; currentPeriod: number; matchStatus: string }; participants: Array<{ participantKey: string; teamId: string | null }>; events: Array<{ id: string }> } }
type PendingAction = { clientEventId: string; matchId: string; participantKey: 'HOME' | 'AWAY'; points: 1 | 2 | 3; period: number; createdAt: string; status: 'pending' | 'rejected' }

export function ScorerConsole({ matchId, sport = 'basketball', initialState }: Props) {
  const [state, setState] = useState(initialState.state ?? { homeScore: 0, awayScore: 0, currentPeriod: 1, matchStatus: 'READY' })
  const [queue, setQueue] = useState<PendingAction[]>([])
  const [online, setOnline] = useState(true)
  const [pending, startTransition] = useTransition()
  useEffect(() => { const update = () => setOnline(navigator.onLine); update(); window.addEventListener('online', update); window.addEventListener('offline', update); return () => { window.removeEventListener('online', update); window.removeEventListener('offline', update) } }, [])
  const send = (action: PendingAction) => postSportScore({ ...action, sport }).then(() => setQueue((q) => q.filter((item) => item.clientEventId !== action.clientEventId))).catch(() => setQueue((q) => q.map((item) => item.clientEventId === action.clientEventId ? { ...item, status: 'rejected' } : item)))
  const score = (participantKey: 'HOME' | 'AWAY', points: 1 | 2 | 3) => startTransition(() => { const action = { clientEventId: crypto.randomUUID(), matchId, participantKey, points, period: state.currentPeriod, createdAt: new Date().toISOString(), status: 'pending' as const }; setState((current) => ({ ...current, [`${participantKey.toLowerCase()}Score`]: current[`${participantKey.toLowerCase()}Score` as 'homeScore' | 'awayScore'] + points, matchStatus: 'LIVE' })); setQueue((q) => [...q, action]); if (online) void send(action) })
  useEffect(() => { if (online) queue.filter((item) => item.status === 'pending').forEach(send) }, [online])
  const sportLabel = sport[0].toUpperCase() + sport.slice(1)
  const periodLabel = sport === 'basketball' ? 'Quarter' : sport === 'volleyball' ? 'Set' : 'Game'
  const pointValues = sport === 'basketball' ? ([1, 2, 3] as const) : ([1] as const)
  return <main className="min-h-screen bg-background px-4 py-8 text-foreground"><div className="mx-auto max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-muted-foreground">{sportLabel} scorer</p><p className="mt-2 text-sm" role="status">{online ? 'Connected' : 'Offline — scores will sync automatically'}{queue.length ? ` · ${queue.length} pending` : ''}</p><div className="mt-5 grid grid-cols-2 gap-3"><ScoreCard label="Home" score={state.homeScore} pointValues={pointValues} onScore={(points) => score('HOME', points)} /><ScoreCard label="Away" score={state.awayScore} pointValues={pointValues} onScore={(points) => score('AWAY', points)} /></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card p-4"><span>{periodLabel} {state.currentPeriod} · {state.matchStatus}</span><div className="flex gap-2">{(sport === 'basketball' ? [1, 2, 3, 4] : [1, 2, 3]).map((period) => <button className="rounded-md border border-border px-3 py-2 text-sm hover:bg-muted" key={period} onClick={() => setState((current) => ({ ...current, currentPeriod: period }))}> {sport === 'basketball' ? 'Q' : sport === 'volleyball' ? 'S' : 'G'}{period}</button>)}<button className="rounded-md border border-border px-3 py-2 text-sm hover:bg-muted" disabled={pending} onClick={() => startTransition(() => undoLastBasketballScore(matchId))}>Undo</button><button className="rounded-md bg-primary px-3 py-2 text-sm text-primary-foreground" disabled={pending} onClick={() => startTransition(() => setBasketballStatus(matchId, state.matchStatus === 'LIVE' ? 'PAUSED' : 'LIVE'))}>{state.matchStatus === 'LIVE' ? 'Pause' : 'Start'}</button></div></div></div></main>
}
function ScoreCard({ label, score, pointValues, onScore }: { label: string; score: number; pointValues: readonly (1 | 2 | 3)[]; onScore: (points: 1 | 2 | 3) => void }) { return <section className="rounded-xl border border-border bg-card p-5 text-center"><p className="text-sm text-muted-foreground">{label}</p><p className="my-4 text-6xl font-semibold tabular-nums">{score}</p><div className="grid grid-cols-3 gap-2">{pointValues.map((points) => <button className="rounded-lg border border-border py-3 font-semibold hover:bg-muted" key={points} onClick={() => onScore(points)}>+{points}</button>)}</div></section> }
