import Link from 'next/link'
import { requireSuperAdmin } from '@/lib/authorization'
import { db } from '@/lib/db'
import { events, users } from '@/lib/db/schema'
import { desc } from 'drizzle-orm'
import { createUser, toggleUser } from './actions'

export default async function UsersPage() {
  const admin = await requireSuperAdmin()
  const [people, eventOptions] = await Promise.all([db.select().from(users).orderBy(desc(users.createdAt)), db.select({ id: events.id, name: events.name }).from(events).orderBy(desc(events.createdAt))])
  return <main className="min-h-screen bg-background px-6 py-10 text-foreground"><div className="mx-auto flex max-w-6xl flex-col gap-8">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/admin" className="text-sm text-muted-foreground hover:text-foreground">← Admin</Link><p className="mt-4 text-sm font-semibold uppercase tracking-[0.2em] text-muted-foreground">Access control</p><h1 className="text-4xl font-semibold tracking-tight">People & scorer accounts</h1><p className="mt-2 text-muted-foreground">Create operator accounts, then assign scorers from each event workspace.</p></div><Link href="/" className="rounded-md border border-border px-4 py-2 text-sm font-medium hover:bg-muted">Workspace</Link></header>
    <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><h2 className="text-lg font-semibold">Add a person</h2><form action={createUser} className="mt-5 grid gap-3 md:grid-cols-5"><input name="displayName" required placeholder="Full name" className="rounded-md border border-input bg-background px-3 py-2 text-sm"/><input name="username" required placeholder="Username" className="rounded-md border border-input bg-background px-3 py-2 text-sm"/><input name="password" required minLength={10} type="password" placeholder="Temporary password" className="rounded-md border border-input bg-background px-3 py-2 text-sm"/><select name="role" defaultValue="SCORER" className="rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="SCORER">Scorer</option><option value="EVENT_ADMIN">Event Admin</option><option value="SUPER_ADMIN">Super Admin</option></select><select name="eventId" defaultValue="" className="rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">No event assignment</option>{eventOptions.map((event) => <option key={event.id} value={event.id}>{event.name}</option>)}</select><button className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:opacity-90" type="submit">Create account</button></form><p className="mt-3 text-xs text-muted-foreground">Use the username and temporary password to sign in. Scorer permissions are assigned per event.</p></section>
    <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="border-b border-border px-6 py-4"><h2 className="font-semibold">Accounts <span className="text-muted-foreground">({people.length})</span></h2></div><div className="divide-y divide-border">{people.map((person) => <div className="flex flex-wrap items-center justify-between gap-4 px-6 py-4" key={person.id}><div><p className="font-medium">{person.displayName}</p><p className="text-sm text-muted-foreground">@{person.username} · {person.role === 'SUPER_ADMIN' ? 'Super Admin' : person.role === 'EVENT_ADMIN' ? 'Event Admin' : 'Scorer'}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${person.isActive ? 'bg-primary/10 text-primary' : 'bg-muted text-muted-foreground'}`}>{person.isActive ? 'Active' : 'Inactive'}</span>{person.id !== admin.id && <form action={toggleUser.bind(null, person.id)}><button className="text-sm font-medium text-muted-foreground hover:text-foreground" type="submit">{person.isActive ? 'Deactivate' : 'Reactivate'}</button></form>}</div></div>)}</div></section>
  </div></main>
}
