import Link from 'next/link'
import { AdminDestination } from '@/components/admin-destination'
import { db } from '@/lib/db'
import { events } from '@/lib/db/schema'
import { desc } from 'drizzle-orm'
import { requireUser } from '@/lib/authorization'
import { listMatches } from '@/lib/db/repositories/matches'

export default async function SchedulePage({ searchParams }: { searchParams: Promise<{ eventId?: string }> }) {
  const user = await requireUser(); const eventRows = await db.select({ id: events.id, name: events.name }).from(events).orderBy(desc(events.createdAt)); const selectedEventId = (await searchParams).eventId; const eventId = eventRows.some((event) => event.id === selectedEventId) ? selectedEventId : eventRows[0]?.id; const matches = eventId ? await listMatches(eventId) : []; const canManage = user.role === 'SUPER_ADMIN' || user.role === 'EVENT_ADMIN'
  return <AdminDestination eyebrow="Workspace" title="Schedule" description="Review the real match schedule for the selected event and open match setup." action={eventId ? <span className="rounded-full border border-border px-3 py-1.5 text-xs text-muted-foreground">{eventRows[0].name}</span> : undefined}>
    {eventId && <form method="get" className="mb-4 flex flex-wrap items-end gap-3 rounded-xl border border-border bg-card p-4"><label className="grid min-w-64 flex-1 gap-2 text-sm"><span className="font-medium">Event workspace</span><select name="eventId" defaultValue={eventId} className="rounded-md border border-input bg-background px-3 py-2">{eventRows.map((event) => <option key={event.id} value={event.id}>{event.name}</option>)}</select></label><button className="rounded-md border border-border px-3 py-2 text-sm font-medium">Switch event</button></form>}{eventId && <div className="mb-4 flex items-center justify-between rounded-xl border border-border bg-card p-4"><p className="text-sm text-muted-foreground">{matches.length} scheduled match{matches.length === 1 ? '' : 'es'}</p>{canManage && <Link href={`/events/${eventId}/matches`} className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Create match</Link>}</div>}
    {!eventId ? <section className="rounded-xl border border-border bg-card p-10 text-center"><p className="font-medium">Create an event first</p></section> : <section className="overflow-hidden rounded-xl border border-border bg-card">{matches.length ? <div className="divide-y divide-border">{matches.map(({ match, sport, court, homeTeam, awayTeam }) => <Link key={match.id} href={`/events/${eventId}/matches/${match.id}`} className="flex flex-wrap items-center justify-between gap-4 p-5 transition-colors hover:bg-muted/30"><div><p className="font-medium">{homeTeam || 'TBD'} <span className="text-muted-foreground">vs</span> {awayTeam || 'TBD'}</p><p className="mt-1 text-xs text-muted-foreground">{sport} · {court || 'Court TBD'}</p></div><div className="text-right"><p className="text-sm">{match.scheduledStart ? new Date(match.scheduledStart).toLocaleString() : 'Time TBD'}</p><p className="mt-1 text-xs text-muted-foreground">{match.status}</p></div></Link>)}</div> : <p className="p-10 text-center text-sm text-muted-foreground">No matches yet. Use Create match to add the first schedule entry.</p>}</section>}
  </AdminDestination>
}
