import Link from 'next/link'
import { listEventsForUser } from '@/lib/db/repositories/events'
import { requireEventAdminWorkspace } from '@/lib/authorization'

export default async function EventAdminPage() {
  const user = await requireEventAdminWorkspace()
  const rows = await listEventsForUser(user.id, false)
  return <div className="flex flex-col gap-8">
    <div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-primary">Event workspace</p><h1 className="text-3xl font-semibold tracking-tight">Choose an event to manage</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Your event administration workspace is separate from platform administration. Open an event to configure its teams, courts, matches, scorers, and results.</p></div>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
      {rows.length ? rows.map(({ event }) => <article key={event.id} className="flex flex-col gap-5 rounded-xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{event.name}</h2><p className="mt-1 text-sm text-muted-foreground">{event.location ?? 'Location TBD'}</p></div><span className="rounded-full border border-border px-2.5 py-1 text-[11px] font-medium text-muted-foreground">{event.status}</span></div><div className="mt-auto flex flex-col gap-3"><p className="text-xs text-muted-foreground">{new Date(event.startDate).toLocaleDateString()}</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-3"><Link href={`/events/${event.id}`} className="rounded-md bg-primary px-3 py-2 text-center text-sm font-semibold text-primary-foreground">Overview</Link><Link href={`/events/${event.id}/matches`} className="rounded-md border border-border px-3 py-2 text-center text-sm font-medium hover:bg-muted">Matches</Link><Link href={`/events/${event.id}/matches`} className="rounded-md border border-border px-3 py-2 text-center text-sm font-medium hover:bg-muted">Results</Link><Link href={`/admin/events/${event.id}`} className="rounded-md border border-border px-3 py-2 text-center text-sm font-medium hover:bg-muted">Teams</Link><Link href={`/admin/events/${event.id}`} className="rounded-md border border-border px-3 py-2 text-center text-sm font-medium hover:bg-muted">Players</Link><Link href={`/admin/events/${event.id}`} className="rounded-md border border-border px-3 py-2 text-center text-sm font-medium hover:bg-muted">Courts</Link><Link href={`/events/${event.id}/scorers`} className="rounded-md border border-border px-3 py-2 text-center text-sm font-medium hover:bg-muted">Scorers</Link><Link href={`/events/${event.id}/matches`} className="rounded-md border border-border px-3 py-2 text-center text-sm font-medium hover:bg-muted">Schedule</Link></div></div></article>) : <div className="rounded-xl border border-dashed border-border p-10 text-center md:col-span-2 xl:col-span-3"><p className="font-medium">No assigned events yet</p><p className="mt-1 text-sm text-muted-foreground">Ask a platform administrator to assign you to an event.</p></div>}
    </section>
  </div>
}
