import { AdminDestination } from '@/components/admin-destination'
import { db } from '@/lib/db'
import { events, teams } from '@/lib/db/schema'
import { desc, eq } from 'drizzle-orm'
import { requireUser } from '@/lib/authorization'
import { createPlayer } from '@/app/admin/resource-actions'
import { getTeamRoster } from '@/lib/db/repositories/players'

export default async function PlayersPage() {
  const user = await requireUser(); const eventRows = await db.select({ id: events.id, name: events.name }).from(events).orderBy(desc(events.createdAt)); const eventId = eventRows[0]?.id; const teamRows = eventId ? await db.select().from(teams).where(eq(teams.eventId, eventId)).orderBy(teams.name) : []; const roster = teamRows.length ? (await Promise.all(teamRows.map(async (team) => ({ team, players: await getTeamRoster(team.id) })))).flatMap((entry) => entry.players.map((item) => ({ ...item.player, team: entry.team, jerseyNumber: item.jerseyNumber }))) : []; const canManage = user.role === 'SUPER_ADMIN' || user.role === 'EVENT_ADMIN'
  return <AdminDestination eyebrow="Workspace" title="Players" description="Add players directly to an event team roster." action={eventId ? <span className="rounded-full border border-border px-3 py-1.5 text-xs text-muted-foreground">{eventRows[0].name}</span> : undefined}>
    {canManage && eventId && teamRows.length > 0 && <form action={createPlayer} className="grid gap-3 rounded-xl border border-border bg-card p-5 md:grid-cols-[1fr_1fr_1fr_160px_auto]"><input type="hidden" name="eventId" value={eventId}/><input name="displayName" required placeholder="Display name" className="rounded-md border border-input bg-background px-3 py-2 text-sm"/><input name="firstName" placeholder="First name" className="rounded-md border border-input bg-background px-3 py-2 text-sm"/><input name="lastName" placeholder="Last name" className="rounded-md border border-input bg-background px-3 py-2 text-sm"/><select name="teamId" required className="rounded-md border border-input bg-background px-3 py-2 text-sm">{teamRows.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select><input name="jerseyNumber" type="number" min="0" max="999" placeholder="#" className="rounded-md border border-input bg-background px-3 py-2 text-sm"/><button className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground md:col-span-5">Add player</button></form>}
    {!eventId ? <section className="rounded-xl border border-border bg-card p-10 text-center"><p className="font-medium">Create an event first</p></section> : !teamRows.length ? <section className="rounded-xl border border-border bg-card p-10 text-center"><p className="font-medium">Add a team before adding players</p><a href="/admin/teams" className="mt-2 inline-block text-sm text-primary">Go to teams</a></section> : <section className="rounded-xl border border-border bg-card p-5">{roster.length ? <div className="divide-y divide-border">{roster.map((player) => <div key={`${player.id}-${player.team.id}`} className="flex items-center justify-between py-3"><div><p className="font-medium">{player.displayName}</p><p className="text-xs text-muted-foreground">{player.team.name}{player.jerseyNumber != null ? ` · #${player.jerseyNumber}` : ''}</p></div></div>)}</div> : <p className="py-8 text-center text-sm text-muted-foreground">No players yet. Use Add player to create a roster entry.</p>}</section>}
  </AdminDestination>
}
